from collections.abc import Callable, Iterable
from typing import overload

from . import af as af, df as df, sf as sf


class SpectralResponse:
    @overload
    def __init__(self, filename: str) -> None: ...

    @overload
    def __init__(self, iter: Iterable[str]) -> None: ...

    def normalize(self) -> SpectralResponse: ...

    def normalized(self) -> SpectralResponse: ...

    def stack(self, other: SpectralResponse) -> None: ...

    def stacked(self, other: SpectralResponse) -> SpectralResponse: ...

    def effective_lambda(self) -> float: ...

class WeightFunction:
    def __init__(self, spectral_filter: Callable[[float], float], wavelength: float, aperture_filter: Callable[[float], float], aperture_scale: float, size: int) -> None: ...

    def __call__(self, altitude: float) -> float: ...

class WeightFunction2d:
    def __init__(self, spectral_filter: Callable[[float], float], wavelength: float, aperture_filter: Callable[[float, float], float], aperture_scale: float, size: int) -> None: ...

    def __call__(self, altitude: float) -> float: ...
