from collections.abc import Callable, Iterable
from typing import overload

from . import af as af, df as df, sf as sf


class SpectralResponse:
    @overload
    def __init__(self, arg: str, /) -> None: ...

    @overload
    def __init__(self, arg: Iterable, /) -> None: ...

    def normalize(self) -> SpectralResponse: ...

    def normalized(self) -> SpectralResponse: ...

    def stack(self, arg: SpectralResponse, /) -> None: ...

    def stacked(self, arg: SpectralResponse, /) -> SpectralResponse: ...

    def effective_lambda(self) -> float: ...

class WeightFunction:
    def __init__(self, arg0: Callable[[float], float], arg1: float, arg2: Callable[[float], float], arg3: float, arg4: int, /) -> None: ...

    def __call__(self, arg: float, /) -> float: ...

class WeightFunction2d:
    def __init__(self, arg0: Callable[[float], float], arg1: float, arg2: Callable[[float, float], float], arg3: float, arg4: int, /) -> None: ...

    def __call__(self, arg: float, /) -> float: ...
