"""Aperture filter submodule"""

from typing import overload


class Circular:
    def __init__(self) -> None: ...

    @overload
    def __call__(self, u: float) -> float: ...

    @overload
    def __call__(self, ux: float, uy: float) -> float: ...

class Annular:
    def __init__(self, obscuration: float) -> None: ...

    @overload
    def __call__(self, u: float) -> float: ...

    @overload
    def __call__(self, ux: float, uy: float) -> float: ...

class CrossAnnular:
    def __init__(self, ratio: float, obscuration_first: float, obscuration_second: float) -> None: ...

    @overload
    def __call__(self, u: float) -> float: ...

    @overload
    def __call__(self, ux: float, uy: float) -> float: ...

class Point:
    def __init__(self) -> None: ...

    @overload
    def __call__(self, u: float) -> float: ...

    @overload
    def __call__(self, ux: float, uy: float) -> float: ...

class Square:
    def __init__(self) -> None: ...

    def __call__(self, ux: float, uy: float) -> float: ...
