from typing import overload


class Circular:
    def __init__(self) -> None: ...

    @overload
    def __call__(self, arg: float, /) -> float: ...

    @overload
    def __call__(self, arg0: float, arg1: float, /) -> float: ...

class Annular:
    def __init__(self, arg: float, /) -> None: ...

    @overload
    def __call__(self, arg: float, /) -> float: ...

    @overload
    def __call__(self, arg0: float, arg1: float, /) -> float: ...

class CrossAnnular:
    def __init__(self, arg0: float, arg1: float, arg2: float, /) -> None: ...

    @overload
    def __call__(self, arg: float, /) -> float: ...

    @overload
    def __call__(self, arg0: float, arg1: float, /) -> float: ...

class Point:
    def __init__(self) -> None: ...

    @overload
    def __call__(self, arg: float, /) -> float: ...

    @overload
    def __call__(self, arg0: float, arg1: float, /) -> float: ...

class Square:
    def __init__(self) -> None: ...

    def __call__(self, arg0: float, arg1: float, /) -> float: ...
