from collections.abc import Callable, Sequence


class DigitalFilter2d:
    def __init__(self, arg0: Callable[[float, float], float], arg1: Sequence[int], /) -> None: ...

    def mix(self) -> DigitalFilter2d: ...

    def mixed(self) -> DigitalFilter2d: ...

    def __call__(self, arg0: float, arg1: float, /) -> float: ...
