from collections.abc import Callable, Sequence


class DigitalFilter2d:
    def __init__(self, fun: Callable[[float, float], float], shape: Sequence[int]) -> None: ...

    def mix(self) -> DigitalFilter2d: ...

    def mixed(self) -> DigitalFilter2d: ...

    def __call__(self, ux: float, uy: float) -> float: ...
