from typing import overload

import pyweif


class Mono:
    def __init__(self) -> None: ...

    def __call__(self, arg: float, /) -> float: ...

    def regular(self, arg: float, /) -> float: ...

class Gauss:
    def __init__(self, arg: float, /) -> None: ...

    def __call__(self, arg: float, /) -> float: ...

    def regular(self, arg: float, /) -> float: ...

class Poly:
    @overload
    def __init__(self, arg0: pyweif.SpectralResponse, arg1: int, /) -> None: ...

    @overload
    def __init__(self, arg0: pyweif.SpectralResponse, arg1: int, arg2: float, /) -> None: ...

    def __call__(self, arg: float, /) -> float: ...

    def regular(self, arg: float, /) -> float: ...

    def normalize(self) -> Poly: ...

    def normalized(self) -> Poly: ...

    def equiv_lambda(self) -> float: ...

    def carrier(self) -> float: ...
