from typing import overload

import pyweif


class Mono:
    def __init__(self) -> None: ...

    def __call__(self, x: float) -> float: ...

    def regular(self, x: float) -> float: ...

class Gauss:
    def __init__(self, fwhm: float) -> None: ...

    def __call__(self, x: float) -> float: ...

    def regular(self, x: float) -> float: ...

class Poly:
    @overload
    def __init__(self, response: pyweif.SpectralResponse, size: int) -> None: ...

    @overload
    def __init__(self, response: pyweif.SpectralResponse, size: int, carrier: float) -> None: ...

    def __call__(self, x: float) -> float: ...

    def regular(self, x: float) -> float: ...

    def normalize(self) -> Poly: ...

    def normalized(self) -> Poly: ...

    def equiv_lambda(self) -> float: ...

    def carrier(self) -> float: ...
